name: deploy
on:
  push:
    branches:
      - workspace
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: egordm/gha-yarn-node-cache@v1
      - name: install
        run: |
          yarn install
      - name: build
        run: |
          yarn build:all
          touch out/.nojekyll
          echo "www.mbsoftware.tokyo" > out/CNAME
        env:
          GITHUB_PAGES: true
      - name: deploy
        uses: peaceiris/actions-gh-pages@v2.3.1
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./out
